inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'

Style/Encoding:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
